### ISSUE TITLE
500 error after installation

### ISSUE THREAD

**Issue by askurashev** [SemanticMediaWiki/SummaryCards#10]
### Setup and configuration

- SUC version: 1.0
- MW version: 1.28
- DB (MySQL etc.): MySQL

### Issue

After hand installation (copy files on server and include in LocalSettings.php) site give 500 server error.

**Comment by kghbln** [comment]
@antohabio Without the information form the server log it will be quite impossible to see what's going on. See [here for help](https://www.mediawiki.org/wiki/Manual:Errors_and_symptoms#You_see_a_Blank_Page)

**Comment by kghbln** [comment]
In case new information arises this may be reopened.
