### ISSUE TITLE
Archive this extension?

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SummaryCards#17]
I think this extension is a) not properly working in recent versions of MediaWiki (1.35 and up) and b) since a very similar functionality is now available wit the [popups extension](https://www.mediawiki.org/wiki/Extension:Popups), the question is if we should archive this extension?

Or is someone using it who believes it has superior features over popups?

**Comment by pppery** [comment]
Agreed.

**Comment by krabina** [comment]
@kghbln can you archive this extension?

**Comment by kghbln** [comment]
I will do this now. I added the following note to the README: This extension was never officially released and has not been maintained for a long time. Moreover, it is no longer compatible with recent MediaWiki or Semantic MediaWiki releases. As a result, it was archived in October 2023.

**Comment by kghbln** [comment]
Closed per https://github.com/SemanticMediaWiki/SummaryCards/issues/17
