### ISSUE TITLE
NewRevisionFromEditComplete hook was removed in 1.37

### ISSUE THREAD

**Issue by pppery** [SemanticMediaWiki/SummaryCards#19]
Still referenced at https://github.com/SemanticMediaWiki/SummaryCards/blob/57881bf4cbd6ddf44e5327d645cb20dbf5979b0a/src/HookRegistry.php#L98

**Comment by kghbln** [comment]
Closed per https://github.com/SemanticMediaWiki/SummaryCards/issues/17
