### ISSUE TITLE
not working on a closed wiki

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SummaryCards#9]
I had to close the wiki I am using SC with $wgGroupPermissions['*']['read'] = false;

What happens now is the message: "Error: readapidenied. You need read permission to use this module." instead of the summary card.
I could not find a "readapi" permission in MW, only a writeapi. Is there a way to grant logged-in users the right to view summery cards?

**Comment by kghbln** [comment]
Closed per https://github.com/SemanticMediaWiki/SummaryCards/issues/17
